### PR TITLE
generate *.tar.gz

### PR DESCRIPTION
**Pull request by Edoardo-Pedicillo**
In this PR, I have added the job `generate *.tar.gz`. 
Maybe it is not the most elegant way, but it works.

### CODE REVIEW

**Comment by AleCandido** [comment]
The job is not required by nor require any other job (`needs:`), so it will run in parallel, and fail for missing content.

**Comment by AleCandido** [comment]
I'm a fan of atomic commits, it make it easier to debug and they become self-documenting (with commit messages), but 10 commits for 8 lines in 5 minutes might be a bit too much...

Please, refrain from committing one line at a time, even though up to now you've done for triggering workflows. There are proper solution for both:
- you can trigger with the button, or with an HTTP request to the GitHub API
- separate commit by logic units

**Comment by Edoardo-Pedicillo** [comment]
> The job is not required by nor require any other job (`needs:`), so it will run in parallel, and fail for missing content.

I made a mistake, `generate *.tar.gz` is not a job, but a step of the job `new-artifact`, so it does not require `needs:`. If you want to see it in action, please look [here](https://github.com/qibogang/qibo/actions/runs/3694011719/jobs/6254709044#step:5:1).

> I'm a fan of atomic commits, it make it easier to debug and they become self-documenting (with commit messages), but 10 commits for 8 lines in 5 minutes might be a bit too much...

In this case, the commits are not intended to trigger the workflows, it will be well documented in that case. Before pushing, I tried the code locally and it worked, but the workflow didn't, so I was forced to push in order to fix the bug.

**Comment by AleCandido** [comment]
Sorry, my bad: I didn't pay too much attention, and I have been deceived by the comment. It is perfectly fine :)

**Review by AleCandido — APPROVED** [review]

**Pull request merged**
